### ISSUE TITLE
Komunikace Client/Server

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#1]
Zařízení komunikačního protokolu **Client/Server**, který bude schopen odesílat potřebná data mezi ovladačem a monitorem. Kde ovladač bude fungovat jako **Server** a monitor jako **Client**.

- [ 8 - 10]h

**Comment by kanakl** [comment]
Analyza zpusobu komunikace. 
- [2]h
Analyza pouziti protokolu TCP a UDP
- [2]h
Castecne zprovozneni komunikace pres TCP
- [2]h
Navazani komunikace pres UDP
- [2]h
