### ISSUE TITLE
Přidaní ECG křivek do GUI

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#10]
Přidaní již vytvořených ECG křivek do GUI.

- [1]h

**Comment by pornosaur** [comment]
Potom, co vytvořím potřebné rozhraní je nutno přidělat grafy do GUI. Přepokládám, že by to mohlo být providitelné do pátku 18.3.

**Comment by BobrZlosyn** [comment]
přidány metody na přidání později přidám i metodu která bude vykreslovat všechny najednou, ale k otestování už to lze použít

**Comment by pornosaur** [comment]
Grafy pridany + mensi upravy [1]h
