### ISSUE TITLE
Dodělat GUI u ovladače

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#14]
Dodělat slidery a reakci na ně. V prezentaci od zadavatele (v Projekt peter.pdf) jsou definovány intervaly jednotlivých sliderů - dodělat.

- [2]h

**Comment by pornosaur** [comment]
Nejlépe do pátka 18.3.

**Comment by BobrZlosyn** [comment]
to už by mělo bejt hotový. uvidíme jak to budě běhat pak za provozu
