### ISSUE TITLE
Příprava přepravky k odeslání dat z ovladače

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#15]
@kanakl vytvořil přepravku pro posílaní dat => vytvořit událost pro naplnění této přepravky a její následné vyslání po síti.

**Comment by pornosaur** [comment]
Nutno do konce úterý 15.3. **UDĚLAT!!!**

**Comment by kanakl** [comment]
Zde je ta přepravka: https://github.com/PETER-project/monitor_vital_functions/blob/master/src/PETER_Communications/com_protocol/VitalData.java
To vyslání po síti ještě nemusíš, ale jenom aby sem při kliknutí na "odeslat" vytvořila přepravka VItalData.

**Comment by BobrZlosyn** [comment]
z větší části splněno už jen dodat grafy :D takže snad dobrý :D
