### ISSUE TITLE
Ovladac - pridat seznam krivek

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#26]
Pridat v GUI u ovladace seznam krivek, ktere jsou napsany v zadani - Projekt peter.pdf.

Ve tride ECGParser jsem napsal staticke cesty, ktere (cestou) odkazuji na jednotlive grafy. Takze pri parsovani dat do pole viz metoda 'loadECGData(cesta)' se do parametru cesta budou predavat ruzne cesty prave z techto nekolik definovanych cest.

- [0.5]h

**Comment by BobrZlosyn** [comment]
přidáno jen je potřeba ujasnit si jak se budou posílat, zda jen po dvou nebo po více

**Comment by BobrZlosyn** [comment]
a chybí cesta k Asystolie

**Comment by pornosaur** [comment]
Cesta k Asystolie chyby, protože je to konstantní fce y=0 - smrt nebo nepripojeni monitoru, ještě přemýšlím, jak tuhle křivku posílat.

Pak jenom nechápu, co myslis s tím posláním - po dvou ? Po vice ?

**Comment by BobrZlosyn** [comment]
no protože teďka je ta přepravka udělaná jen pro dvě ty křivky - ecg1 a ecg2 tak by vlastně musel poslat víckrát co chce

**Comment by kanakl** [comment]
tuto asi zatim neřeš to se s nim musíme pak domluvit jak to chce s těma křivkama a pak se to dyštak předělá

**Comment by pornosaur** [comment]
V tom pripade je prepravka udelana spatne, kdyz si prectes dokumentacni komentar toho parseru, tak vraci pole float[][], kde na kazde radce je prvek 0 - cas, 1 - ecg1, 2 - ecg2. Takze se rovnou posilaji obe (pokud je dany soubor/krivka obsahuje). To znamena -> predelat i prepravku.
