### ISSUE TITLE
DODELAT defibrilator !

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#28]
Udelat defibrilator dle zadani Projekt peter.pdf !!! Je to slide c.10

- [2]h

**Comment by BobrZlosyn** [comment]
defibrilator by měl být skoro hotov ale je nutný vyzkoušet ty vlákna i na jinym PC, protože u mě to občas blbne, že to funguje i když jinde ne

**Comment by BobrZlosyn** [comment]
doděláno už se jen vyjasní v úterý co všechno tam bude chtít nastavit
