### ISSUE TITLE
Oprava komunikace

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#36]
Pokud bezi monitor a ukonci se ovladac a znova se spusti, tak pri odeslani dat jiz nenavaze komunikace se spustenym monitorem.

- [1-2]h

**Comment by kanakl** [comment]
Opraveno, ale je nutne jeste dodelat i v obracenem poradi
- [0.5]h

**Comment by kanakl** [comment]
Vyreseno. V budoucnu mozna poupravit

- [1.5]h
