### ISSUE TITLE
Nefunguje odesilani

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#38]
Pri poslednim commitu ohledne komunikace nefunguje odesilani dat.

[INFO - Server.run()] - Server(192.168.0.12) is running on port55555
Loading data from data/ecg/c_NormalSinRhythm.csv
    Data was succesfully loaded!
[INFO - Server.sendData()] - Client disconnect
[INFO - Server.run()] - Server(192.168.0.12) is running on port55555

**Comment by kanakl** [comment]
Chyba nastava pokud se jako prvni zapne monitor a pak az ovladac. V opacnem poradi to funguje. Chybu opravim

**Comment by kanakl** [comment]
Chyba opravena
