### ISSUE TITLE
Nenastavuji se vsechny parametry

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#39]
Na GUI monitoru se nenastavuji veskere hodnoty odeslane z ovladace.

- [0.1]h

**Comment by pornosaur** [comment]
Porad se tam nenstavuje rucne nastaveny tlak na ovladaci! + dopln straveny cas

**Comment by BobrZlosyn** [comment]
pardon moje chyba :// teď se tam nezobrazuje jen teplota kterou nevim kam dát zatim 
doba [4h]
