### ISSUE TITLE
Pridani funkce defibrilatoru

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#42]
Pridat funkce defibrilatoru viz domluva se zachranarem - metronom, labely (barevnost) impedance, zamitnuti vyboje pri spatne analyze

- [1-2]h

**Comment by pornosaur** [comment]
Je to tu 14 dni a porad to neni hotove! Je docela dulezite, aby ten defibrilator pracoval na stopro!!!

**Comment by BobrZlosyn** [comment]
všechno až na ten metronom by mělo bejt připravený :) jen se pak musíme domluvit jak se bude měnit ten graf při tom nepovedém pokusu

**Comment by BobrZlosyn** [comment]
a nevim co má měnit ten metronom tak to budu ještě zkoumat :/

**Comment by kanakl** [comment]
pro metronom tam bude jenom tlačítko kterým to zapneš a spustí tikání. Frekvenci ale nevim, řikal něco o 100 úderech
