### ISSUE TITLE
Pridani funkci pro ovladac

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#43]
Pridani seznamu nasledujicich akci do seznamu (v novem tabu vedle krivek) s nastavenou casovou prodlevou. Pridani labelu, ktery bude informovat, jestli jsou zarizeni spojeny. Moznost nastaveni impedance pro monitor - nizka, OK, vysoka -> moznost vyboje ci nikoliv.

- [2]h

**Comment by pornosaur** [comment]
To same jako defibrilator, jinak receno je to pro def. dulezita soucast (impedance). Po 14 dnech porad neni hotove, napravit!

**Comment by BobrZlosyn** [comment]
popravdě absolutně netušim co ta impedance ovlivňuje :D

**Comment by kanakl** [comment]
to bylo to s tim když je chlupatej a tak. to se asi bude nastavovat na ovladači ale nejsem si jistej

**Comment by BobrZlosyn** [comment]
to jo no ale jak se to pak projeví na tom monitoru :O

**Comment by pornosaur** [comment]
Jde o to, ze na ovladaci bude moc nastavit jaka bude impedance - nizka, normal, vysoka a na monitoru bude pouze barevne oznaceno, co je aktivni. Pri nizke a vysoke by nemel byt umoznen podan vyboj, pokud is pamatuju.

**Comment by BobrZlosyn** [comment]
ahaaa super tak to dodělam :)

**Comment by BobrZlosyn** [comment]
mělo by být všechno funkční ale musí se to pak ještě otestovat :)
