### ISSUE TITLE
Zbareveni pozadi hodnot 

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#44]
Pri kritickych hodnotach (mimo interval, ktery je uveden u kazdeho parametru) obarvit pozadi na jemne cervenou -> upozorneni. Obarveni parametru dle monitoru v prezentaci Projekt peter.pdf

- [1]h

**Comment by pornosaur** [comment]
Taky nutno dodelat, ale nejdrive ten defibrilator.

**Comment by BobrZlosyn** [comment]
zabarvení hotovo už se jen budou vylaďovat barvičky
