### ISSUE TITLE
Oprava potencionalnich bugu

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#49]
Doopraveni dalsich bezpecnostnich prvku, bugu komunikace (ruzne vyjimky a pady o kterych vis).

- [3]h

**Comment by kanakl** [comment]
Dodelani identifikace komunikace

**Comment by kanakl** [comment]
Identifikace dodelana

- [0.5] h

**Comment by kanakl** [comment]
optimalizace pripojeni

- [0.5]h
