### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#50]
Pridani fullscreenu pro monitor - nejlepe na stisk nejakeho z tlacitek (kvuli testovani, aby se mi to primarne neprepinalo hend do fullscreenu)

- [0.5]h

**Comment by BobrZlosyn** [comment]
fullscreen při zapnutí je zatim zakomentovaný a fulscreen v aplikaci lze zapnout v menu či ctrl+f5
