### ISSUE TITLE
Kolisani tepu

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#51]
Pridat, aby nahodne kolisala tepova frekvence pacienta.

- [1]h

**Comment by BobrZlosyn** [comment]
ouč kolísání hodnot jsem teď udělal :) to jsem se přehlídnul :/

**Comment by pornosaur** [comment]
Nevadi, dopln straveny cas. Ja to jeste osetrim, aby to makalo lepe.
