### ISSUE TITLE
Neukonceni clienta

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#60]
Kdy se zapne monitor + ovladac, tak pri ukonceni monitoru se neukonci client. Pokud se zapne jenom monitor a vypne se, tak se vypne. Zkousel jsem, jestli tam nebezi nejake moje vlakno (vykreslovani nebo vypocet bodu), ale oboji se ukonci, takze to vypada, ze je to na strane komunikace.
Furt to vypisuje: [INFO - Client.recieveData()] - Client exit

**Comment by kanakl** [comment]
Opraveno
