### ISSUE TITLE
Zabezpečování komunikačního protokolu

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#7]
Nutno zabebezpečit komunikační protokol. Zajištění, aby data vždy byly v pořádku přijaty a co nejvíce eliminovat nestabilitu.

- [5 - 6]h

**Comment by kanakl** [comment]
Identifikace odpojeni klienta nebo servru

- [1]h

**Comment by kanakl** [comment]
Pri zavreni gui oken se nevypinal klient resp server. Opraveno

- [1]h

**Comment by kanakl** [comment]
Oprava chyby pri zavreni monitoru.

- [1.5]h

**Comment by kanakl** [comment]
Oprava chyby pri odeslani dat nepripojenemu monitou

- [0.5]h

**Comment by kanakl** [comment]
Dodelana moznost pro funkci spojeni pri obsazeni portu 

- [1]h
