### ISSUE TITLE
Ovladac - reset posuvniku

### ISSUE THREAD

**Issue by kanakl** [PETER-project/monitor_vital_functions#72]
Po odeslani dat se resetuji vsechny posuvniky do puvodni pozice misto toho aby zustaly na posledni zvolene pozici

**Comment by BobrZlosyn** [comment]
tak oni se ty hodnoty vynulují pokud máš ve frontě vybráno to co se zrovna odesílá a protože se to odešle tak jsem tam dal aby se to vynulovalo protože to již neni zvolený a taky se tím pozná že už to není ve frontě.

**Comment by kanakl** [comment]
No asi byl bylo dobrý aby ty hodnoty zůstávali protože kdyby chtěl třeba znovu odeslat jenom se změnou tepu tak by musel všechno znovu nastavovat

**Comment by BobrZlosyn** [comment]
dobrá tak by to mělo být změněno :)

**Comment by kanakl** [comment]
Posuvniky a vyber krivky se stale resetuji

**Comment by BobrZlosyn** [comment]
teď už by to mělo bejt akorát nechávam nulovat tu křivku
