### ISSUE TITLE
Hlaska pri spusteni monitoru

### ISSUE THREAD

**Issue by kanakl** [PETER-project/monitor_vital_functions#73]
Pri spusteni monitoru se v konzoli vypise tato hlaska:

Dub 21, 2016 4:27:13 ODP. com.sun.javafx.css.parser.CSSParser term
WARNING: CSS Error parsing '*{-fx-background-color: ;}: Unexpected token ';' at [1,24]

Program ale funguje

**Comment by BobrZlosyn** [comment]
opravené
