### ISSUE TITLE
Ovladac - rozdilne mezery mezi slidery

### ISSUE THREAD

**Issue by kanakl** [PETER-project/monitor_vital_functions#76]
Pri fullscreenu ovladace jsou videt rozdilne mezery mezi slidery. Od Hear do RR jsou stejne a pak jine u SPo2 - Temp. Mozna je to zpusobene tema ruznyma panelama jak jsme se jednou o tom bavili

**Comment by BobrZlosyn** [comment]
vyřešené :)
