### ISSUE TITLE
Ladění GUI

### ISSUE THREAD

**Issue by pornosaur** [PETER-project/monitor_vital_functions#9]
Doladení detailů GUI dle domluvených požadavků.

- [5]h

**Comment by BobrZlosyn** [comment]
oprava chyby v GUI

- [1]h

udělání GUI pro ovladač 

- [2]h

**Comment by pornosaur** [comment]
Sem do ladění ještě přidej ošetření těch intervalů u monitoru (barevně odlišné) + další úpravy => aby se to, co nejvíce podobalo tomu reálnemu monitoru.
